name: Build docker image
permissions: write-all
on:
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        working-directory: ./src 
        run: |
             docker build . --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
             docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
