name: Build docker image

# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Build docker image'

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
      - 'releases/**'      
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        working-directory: ./src 
        run: |
             docker build . --tag ghcr.io/${{ github.repository_owner }}/satellite-stream-links:latest
             docker push ghcr.io/${{ github.repository_owner }}/satellite-stream-links:latest
