name: JSON Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
      - 'releases/**'      

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Validate JSON
      run: |
        if jq empty < src/live_streams.json; then
          echo "JSON is valid."
        else
          echo "JSON is invalid."
          exit 1
        fi